### ISSUE TITLE
Wordcloud russian support

### ISSUE THREAD

**Issue by nolines** [zingchart/ZingChart-AngularJS#12]
russian languages not recognized in wordcloud.

**Comment by nolines** [comment]
not only russian and turkish speacial characters not supported. i guess there is a UTF-8 problem.

**Comment by mike-schultz** [comment]
Hi there, that looks to be an issue with the ZingChart library itself rather than this AngularJS directive. Please direct all library related inquiries to support@zingchart.com, as that is the best way to get in touch with library support (I believe yourself or one of your team members has contacted us through that channel.)
