### ISSUE TITLE
Webpack Zingchart-AngularJS integration

### ISSUE THREAD

**Issue by jaimemateo** [zingchart/ZingChart-AngularJS#22]
I've been using ZingChart-AngularJS for more than a year and always worked fine. Now I've moved my app from Broccoli to Webpack to bundle my files. 
After installing ZingChart and ZingChart-AngularJS through npm and require() both packages in my main .js file, I cannot see the charts in the app rendered. There are no errors in the console, but if I inspect the chart element in the view, it seems it didn't executed the logic to render the values. 

I was just wondering if I'm missing any special configuration for Webpack.

Thanks for time and help.

**Comment by gnardecky** [comment]
We currently have an issue open with System.js and how they bundle our library. This issue was brought up in chrome 58 and its possible any webpack updates could contain similar issues. 

I assure you we are looking into these bugs from the tools. While we wait we are doing our best to find out a solution. Please contact support@zingchart.com directly for direct contact with us in a timely manner.

**Comment by ganipadela** [comment]
Any update on this ?

**Comment by jaimemateo** [comment]
After several trials, the problem wasn't with the import of the library but the way of render it. So right now this is how it is working for me:

In the HTML I declare the directive like this:

`<div id="chart-1" zingchart="" zc-width="100%" zc-height="100%" zc-json="vm.myJson"></div>`

Then, I render it like this in the controller:

`zingchart.render({
          id : 'chart-1'
          data : vm.myJson
        })`

I had something similar before but wasn't working. It might be I was missing **zingchart=""** in the HTML but not sure, this was some weeks ago...
